# Generated by Django 5.0.1 on 2024-01-16 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('engine', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
                ('user', models.CharField(max_length=191)),
                ('host', models.CharField(max_length=191)),
                ('port', models.IntegerField()),
                ('password', models.CharField(max_length=191)),
                ('options', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=191)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dbdetails')),
            ],
            options={
                'unique_together': {('name', 'db')},
            },
        ),
    ]
